  export const paisesOptions = [
  { value: "ERROR", label: "Select country" },
  { value: "AFGHANISTAN", label: "AFGHANISTAN" },
  { value: "ÅLAND ISLANDS", label: "ÅLAND ISLANDS" },
  { value: "ALBANIA", label: "ALBANIA" },
  { value: "ALGERIA", label: "ALGERIA" },
  { value: "ANDORRA", label: "ANDORRA" },
  { value: "ANGOLA", label: "ANGOLA" },
  { value: "ANGUILLA", label: "ANGUILLA" },
  { value: "ANTIGUA AND BARBUDA", label: "ANTIGUA AND BARBUDA" },
  { value: "ARGENTINA", label: "ARGENTINA" },
  { value: "ARMENIA", label: "ARMENIA" },
  { value: "ARUBA", label: "ARUBA" },
  { value: "AUSTRALIA", label: "AUSTRALIA" },
  { value: "AUSTRIA", label: "AUSTRIA" },
  { value: "AZERBAIJAN", label: "AZERBAIJAN" },
  { value: "BAHAMAS", label: "BAHAMAS" },
  { value: "BAHRAIN", label: "BAHRAIN" },
  { value: "BANGLADESH", label: "BANGLADESH" },
  { value: "BARBADOS", label: "BARBADOS" },
  { value: "BELARUS", label: "BELARUS" },
  { value: "BELGIUM", label: "BELGIUM" },
  { value: "BELIZE", label: "BELIZE" },
  { value: "BENIN", label: "BENIN" },
  { value: "BERMUDA", label: "BERMUDA" },
  { value: "BHUTAN", label: "BHUTAN" },
  { value: "BOLIVIA", label: "BOLIVIA" },
  { value: "BOSNIA AND HERZEGOVINA", label: "BOSNIA AND HERZEGOVINA" },
  { value: "BOTSWANA", label: "BOTSWANA" },
  { value: "BRAZIL", label: "BRAZIL" },
  { value: "BRITISH INDIAN OCEAN TERRITORY", label: "BRITISH INDIAN OCEAN TERRITORY" },
  { value: "BRITISH VIRGIN ISLANDS", label: "BRITISH VIRGIN ISLANDS" },
  { value: "BRUNEI DARUSSALAM", label: "BRUNEI DARUSSALAM" },
  { value: "BULGARIA", label: "BULGARIA" },
  { value: "BURKINA FASO", label: "BURKINA FASO" },
  { value: "BURUNDI", label: "BURUNDI" },
  { value: "CAMBODIA", label: "CAMBODIA" },
  { value: "CAMEROON", label: "CAMEROON" },
  { value: "CANADA", label: "CANADA" },
  { value: "CAPE VERDE", label: "CAPE VERDE" },
  { value: "CAYMAN ISLANDS", label: "CAYMAN ISLANDS" },
  { value: "CENTRAL AFRICAN REPUBLIC", label: "CENTRAL AFRICAN REPUBLIC" },
  { value: "CHAD", label: "CHAD" },
  { value: "CHILE", label: "CHILE" },
  { value: "CHINA", label: "CHINA" },
  { value: "CHRISTMAS ISLAND", label: "CHRISTMAS ISLAND" },
  { value: "COCOS (KEELING) ISLANDS", label: "COCOS (KEELING) ISLANDS" },
  { value: "COLOMBIA", label: "COLOMBIA" },
  { value: "COMOROS", label: "COMOROS" },
  { value: "CONGO, DEMOCRATIC REPUBLIC OF (DRC)", label: "CONGO, DEMOCRATIC REPUBLIC OF (DRC)" },
  { value: "CONGO, REPUBLIC OF (ROC)", label: "CONGO, REPUBLIC OF (ROC)" },
  { value: "COOK ISLANDS", label: "COOK ISLANDS" },
  { value: "COSTA RICA", label: "COSTA RICA" },
  { value: "CROATIA", label: "CROATIA" },
  { value: "CUBA", label: "CUBA" },
  { value: "CURACAO", label: "CURACAO" },
  { value: "CYPRUS", label: "CYPRUS" },
  { value: "CZECH REPUBLIC", label: "CZECH REPUBLIC" },
  { value: "DENMARK", label: "DENMARK" },
  { value: "DJIBOUTI", label: "DJIBOUTI" },
  { value: "DOMINICA", label: "DOMINICA" },
  { value: "DOMINICAN REPUBLIC", label: "DOMINICAN REPUBLIC" },
  { value: "ECUADOR", label: "ECUADOR" },
  { value: "EGYPT", label: "EGYPT" },
  { value: "EL SALVADOR", label: "EL SALVADOR" },
  { value: "EQUATORIAL GUINEA", label: "EQUATORIAL GUINEA" },
  { value: "ERITREA", label: "ERITREA" },
  { value: "ESTONIA", label: "ESTONIA" },
  { value: "ESWATINI", label: "ESWATINI" },
  { value: "ETHIOPIA", label: "ETHIOPIA" },
  { value: "FALKLAND ISLANDS (MALVINAS)", label: "FALKLAND ISLANDS (MALVINAS)" },
  { value: "FAROE ISLANDS", label: "FAROE ISLANDS" },
  { value: "FEDERATED STATES OF MICRONESIA", label: "FEDERATED STATES OF MICRONESIA" },
  { value: "FIJI", label: "FIJI" },
  { value: "FINLAND", label: "FINLAND" },
  { value: "FRANCE", label: "FRANCE" },
  { value: "FRENCH GUIANA", label: "FRENCH GUIANA" },
  { value: "GABON", label: "GABON" },
  { value: "GAMBIA", label: "GAMBIA" },
  { value: "GEORGIA", label: "GEORGIA" },
  { value: "GERMANY", label: "GERMANY" },
  { value: "GHANA", label: "GHANA" },
  { value: "GIBRALTAR", label: "GIBRALTAR" },
  { value: "GREECE", label: "GREECE" },
  { value: "GREENLAND", label: "GREENLAND" },
  { value: "GRENADA", label: "GRENADA" },
  { value: "GUADELOUPE", label: "GUADELOUPE" },
  { value: "GUAM", label: "GUAM" },
  { value: "GUATEMALA", label: "GUATEMALA" },
  { value: "GUERNSEY", label: "GUERNSEY" },
  { value: "GUINEA", label: "GUINEA" },
  { value: "GUINEA-BISSAU", label: "GUINEA-BISSAU" },
  { value: "GUYANA", label: "GUYANA" },
  { value: "HAITI", label: "HAITI" },
  { value: "HONDURAS", label: "HONDURAS" },
  { value: "HONG KONG SAR, CHINA", label: "HONG KONG SAR, CHINA" },
  { value: "HUNGARY", label: "HUNGARY" },
  { value: "ICELAND", label: "ICELAND" },
  { value: "INDIA", label: "INDIA" },
  { value: "INDONESIA", label: "INDONESIA" },
  { value: "IRAN", label: "IRAN" },
  { value: "IRAQ", label: "IRAQ" },
  { value: "IRELAND", label: "IRELAND" },
  { value: "ISLE OF MAN", label: "ISLE OF MAN" },
  { value: "ISRAEL", label: "ISRAEL" },
  { value: "ITALY", label: "ITALY" },
  { value: "IVORY COAST", label: "IVORY COAST" },
  { value: "JAMAICA", label: "JAMAICA" },
  { value: "JAPAN", label: "JAPAN" },
  { value: "JERSEY", label: "JERSEY" },
  { value: "JORDAN", label: "JORDAN" },
  { value: "KAZAKHSTAN", label: "KAZAKHSTAN" },
  { value: "KENYA", label: "KENYA" },
  { value: "KIRIBATI", label: "KIRIBATI" },
  { value: "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF", label: "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF" },
  { value: "KOREA, REPUBLIC OF", label: "KOREA, REPUBLIC OF" },
  { value: "KUWAIT", label: "KUWAIT" },
  { value: "KYRGYZSTAN", label: "KYRGYZSTAN" },
  { value: "LAO PDR", label: "LAO PDR" },
  { value: "LATVIA", label: "LATVIA" },
  { value: "LEBANON", label: "LEBANON" },
  { value: "LESOTHO", label: "LESOTHO" },
  { value: "LIBERIA", label: "LIBERIA" },
  { value: "LIBYA", label: "LIBYA" },
  { value: "LIECHTENSTEIN", label: "LIECHTENSTEIN" },
  { value: "LITHUANIA", label: "LITHUANIA" },
  { value: "LUXEMBOURG", label: "LUXEMBOURG" },
  { value: "MACAO SAR, CHINA", label: "MACAO SAR, CHINA" },
  { value: "MADAGASCAR", label: "MADAGASCAR" },
  { value: "MALAWI", label: "MALAWI" },
  { value: "MALAYSIA", label: "MALAYSIA" },
  { value: "MALDIVES", label: "MALDIVES" },
  { value: "MALI", label: "MALI" },
  { value: "MALTA", label: "MALTA" },
  { value: "MARSHALL ISLANDS", label: "MARSHALL ISLANDS" },
  { value: "MARTINIQUE", label: "MARTINIQUE" },
  { value: "MAURITANIA", label: "MAURITANIA" },
  { value: "MAURITIUS", label: "MAURITIUS" },
  { value: "MAYOTTE", label: "MAYOTTE" },
  { value: "MEXICO", label: "MEXICO" },
  { value: "MONACO", label: "MONACO" },
  { value: "MONGOLIA", label: "MONGOLIA" },
  { value: "MONTENEGRO", label: "MONTENEGRO" },
  { value: "MONTSERRAT", label: "MONTSERRAT" },
  { value: "MOROCCO", label: "MOROCCO" },
  { value: "MOZAMBIQUE", label: "MOZAMBIQUE" },
  { value: "MYANMAR", label: "MYANMAR" },
  { value: "NAMIBIA", label: "NAMIBIA" },
  { value: "NAURU", label: "NAURU" },
  { value: "NEPAL", label: "NEPAL" },
  { value: "NETHERLANDS", label: "NETHERLANDS" },
  { value: "NEW CALEDONIA", label: "NEW CALEDONIA" },
  { value: "NEW ZEALAND", label: "NEW ZEALAND" },
  { value: "NICARAGUA", label: "NICARAGUA" },
  { value: "NIGER", label: "NIGER" },
  { value: "NIGERIA", label: "NIGERIA" },
  { value: "NIUE", label: "NIUE" },
  { value: "NORFOLK ISLAND", label: "NORFOLK ISLAND" },
  { value: "NORTH MACEDONIA", label: "NORTH MACEDONIA" },
  { value: "NORWAY", label: "NORWAY" },
  { value: "OMAN", label: "OMAN" },
  { value: "PAKISTAN", label: "PAKISTAN" },
  { value: "PALAU", label: "PALAU" },
  { value: "PALESTINE", label: "PALESTINE" },
  { value: "PANAMA", label: "PANAMA" },
  { value: "PAPUA NEW GUINEA", label: "PAPUA NEW GUINEA" },
  { value: "PARAGUAY", label: "PARAGUAY" },
  { value: "PERU", label: "PERU" },
  { value: "PHILIPPINES", label: "PHILIPPINES" },
  { value: "POLAND", label: "POLAND" },
  { value: "PORTUGAL", label: "PORTUGAL" },
  { value: "PUERTO RICO", label: "PUERTO RICO" },
  { value: "QATAR", label: "QATAR" },
  { value: "RÉUNION", label: "RÉUNION" },
  { value: "ROMANIA", label: "ROMANIA" },
  { value: "RUSSIAN FEDERATION", label: "RUSSIAN FEDERATION" },
  { value: "RWANDA", label: "RWANDA" },
  { value: "SAINT BARTHÉLEMY", label: "SAINT BARTHÉLEMY" },
  { value: "SAINT HELENA", label: "SAINT HELENA" },
  { value: "SAINT KITTS AND NEVIS", label: "SAINT KITTS AND NEVIS" },
  { value: "SAINT LUCIA", label: "SAINT LUCIA" },
  { value: "SAINT MARTIN (FRENCH PART)", label: "SAINT MARTIN (FRENCH PART)" },
  { value: "SAINT PIERRE AND MIQUELON", label: "SAINT PIERRE AND MIQUELON" },
  { value: "SAINT VINCENT AND GRENADINES", label: "SAINT VINCENT AND GRENADINES" },
  { value: "SAMOA", label: "SAMOA" },
  { value: "SAN MARINO", label: "SAN MARINO" },
  { value: "SAO TOME AND PRINCIPE", label: "SAO TOME AND PRINCIPE" },
  { value: "SAUDI ARABIA", label: "SAUDI ARABIA" },
  { value: "SENEGAL", label: "SENEGAL" },
  { value: "SERBIA", label: "SERBIA" },
  { value: "SEYCHELLES", label: "SEYCHELLES" },
  { value: "SIERRA LEONE", label: "SIERRA LEONE" },
  { value: "SINGAPORE", label: "SINGAPORE" },
  { value: "SINT MAARTEN (DUTCH PART)", label: "SINT MAARTEN (DUTCH PART)" },
  { value: "SLOVAKIA", label: "SLOVAKIA" },
  { value: "SLOVENIA", label: "SLOVENIA" },
  { value: "SOLOMON ISLANDS", label: "SOLOMON ISLANDS" },
  { value: "SOMALIA", label: "SOMALIA" },
  { value: "SOUTH AFRICA", label: "SOUTH AFRICA" },
  { value: "SOUTH SUDAN", label: "SOUTH SUDAN" },
  { value: "SPAIN", label: "SPAIN" },
  { value: "SRI LANKA", label: "SRI LANKA" },
  { value: "SUDAN", label: "SUDAN" },
  { value: "SURINAME", label: "SURINAME" },
  { value: "SWEDEN", label: "SWEDEN" },
  { value: "SWITZERLAND", label: "SWITZERLAND" },
  { value: "SYRIAN ARAB REPUBLIC (SYRIA)", label: "SYRIAN ARAB REPUBLIC (SYRIA)" },
  { value: "TAIWAN, REPUBLIC OF CHINA", label: "TAIWAN, REPUBLIC OF CHINA" },
  { value: "TAJIKISTAN", label: "TAJIKISTAN" },
  { value: "TANZANIA, UNITED REPUBLIC OF", label: "TANZANIA, UNITED REPUBLIC OF" },
  { value: "THAILAND", label: "THAILAND" },
  { value: "TIMOR-LESTE", label: "TIMOR-LESTE" },
  { value: "TOGO", label: "TOGO" },
  { value: "TOKELAU", label: "TOKELAU" },
  { value: "TONGA", label: "TONGA" },
  { value: "TRINIDAD AND TOBAGO", label: "TRINIDAD AND TOBAGO" },
  { value: "TUNISIA", label: "TUNISIA" },
  { value: "TURKIYE", label: "TURKIYE" },
  { value: "TURKMENISTAN", label: "TURKMENISTAN" },
  { value: "TURKS AND CAICOS ISLANDS", label: "TURKS AND CAICOS ISLANDS" },
  { value: "TUVALU", label: "TUVALU" },
  { value: "UGANDA", label: "UGANDA" },
  { value: "UKRAINE", label: "UKRAINE" },
  { value: "UNITED ARAB EMIRATES", label: "UNITED ARAB EMIRATES" },
  { value: "UNITED KINGDOM", label: "UNITED KINGDOM" },
  { value: "UNITED STATES OF AMERICA", label: "UNITED STATES OF AMERICA" },
  { value: "URUGUAY", label: "URUGUAY" },
  { value: "UZBEKISTAN", label: "UZBEKISTAN" },
  { value: "VANUATU", label: "VANUATU" },
  { value: "VENEZUELA (BOLIVARIAN REPUBLIC)", label: "VENEZUELA (BOLIVARIAN REPUBLIC)" },
  { value: "VIET NAM", label: "VIET NAM" },
  { value: "WESTERN SAHARA", label: "WESTERN SAHARA" },
  { value: "YEMEN", label: "YEMEN" },
  { value: "ZAMBIA", label: "ZAMBIA" },
  { value: "ZIMBABWE", label: "ZIMBABWE" }
  ]
  export const roleOptions = [
    { value: "Chairman", label: "Chairman" },
    { value: "Vice-Chairman", label: "Vice-Chairman" },
    { value: "Secretary", label: "Secretary" },
    { value: "Treasurer", label: "Treasurer" },
    { value: "Director", label: "Director" },

  ]
  export const estructuraJurOptions = [
    { value: "45", label: "Other" },
    { value: "41", label: "private Entity" },
    { value: "42", label: "State/governmental (public-sector entities, in general)" },
    { value: "43", label: "Semi- state/governmental entity (owned at least 20% by government or international entity)" },
    { value: "44", label: "Publicly traded entity (stock exchange)" },
  ]
  export const actividadOptions = [
    { value: "51", label: "Other" },
    { value: "41", label: "Reinsurance (retrocessionaries)" },
    { value: "43", label: "Insurance (cedents)" },
    { value: "46", label: "Brokers / intermediaries (or equivalent)" },
    { value: "47", label: "Managing General Agents (MGAs, or equivalent)" },
    { value: "48", label: "Office administrative services (vendor)" },
    { value: "49", label: "Marketing related services (vendor)" },
    { value: "50", label: "Technology related services (vendor)" },
  ]
  export const constitutionOptions = [
    { value: "11", label: "Less than 2 year" },
    { value: "12", label: "Between 2 and 10 years" },
    { value: "13", label: "More than 10 years" },
  ]
  export const pepOptions = [
    { value: "21", label: "No, I am not PEP - Politically exposed person" },
    { value: "22", label: "Yes, I am PEP - Politically exposed person (by tenure or family)" },
    { value: "23", label: "Yes, I am PEP - Politically exposed person (by position)" },
  ]
  export const governmentalentityOptions = [
    { value: "23", label: "Yes, We are state-governmental (public-sector entities, in general)" },
    { value: "24", label: "Yes, We are semi state-governmental entity (owned at least 20% by government or international entity)" },
    { value: "25", label: "No, we are not state / governmental or semi-state/ governmental controlled entity" },
  ]
  export const sourceFundsOptions = [
    { value: "11", label: "Business mainly conducted (> 50%) in the country of registration" },
    { value: "12", label: "Business conducted both in the country of registration and in other countries (50%/50%)" },
    { value: "13", label: "Business mainly conducted (> 50%) outside the country of registration" },
  ]
  export const annualIncomeOptions = [
    { value: "21", label: "Up to 10,000,000 US$" },
    { value: "22", label: "10,000,000 - 50,000,000 US$" },
    { value: "23", label: "50,000,000 - 100,000,000 US$" },
    { value: "24", label: "100,000,000 US$ and more" },
    { value: "25", label: "Not Applicable" },
  ]

  export const ratingOptions = [
    { value: "AAA", label: "AAA" },
    { value: "AA", label: "AA" },
    { value: "A", label: "A" },
    { value: "BBB", label: "BBB" },
    { value: "BB", label: "BB" },
    { value: "B", label: "B" },
    { value: "CCC", label: "CCC" },
    { value: "CC", label: "CC" },
    { value: "C", label: "C" },
    { value: "D", label: "D" },
  ] 
  export const canalIngresoOptions = [
    { value: "41", label: "Marketing channels" },
    { value: "42", label: "Networking event or business networking" },
    { value: "43", label: "Referral based on a positive recommendation" },
    { value: "44", label: "Market research / Awareness" },
    { value: "45", label: "Employee of Active Re" },
    { value: "46", label: "Board Member of Active Re" },
    { value: "47", label: "Other" },
  ]

  export const yesNoOptions = [
    { value: "s", label: "Yes" },
    { value: "n", label: "No" },
  ]
  export const contactsActive = [
    { value: "IT, Finance, Treasury, HR and other non-commercial departments", label: "IT, Finance, Treasury, HR and other non-commercial departments" },
    { value: "ALEKSANDR MAZHOROV", label: "ALEKSANDR MAZHOROV" },
    { value: "ALEKSEI DEMKIN", label: "ALEKSEI DEMKIN" },
    { value: "ANNA ALEKSANDROVNA ROMANOVA", label: "ANNA ALEKSANDROVNA ROMANOVA" },
    { value: "ARTEM USHAKOV", label: "ARTEM USHAKOV" },
    { value: "DANIEL DAGNINO", label: "DANIEL DAGNINO" },
    { value: "EKATERINA GURYLEVA", label: "EKATERINA GURYLEVA" },
    { value: "ERIK WILLIAM FEIGELSSON", label: "ERIK WILLIAM FEIGELSSON" },
    { value: "ESTEBAN MADERO CRUMP", label: "ESTEBAN MADERO CRUMP" },
    { value: "HUMBERTO RIQUELME", label: "HUMBERTO RIQUELME" },
    { value: "ISABEL KARINA LAM SIU", label: "ISABEL KARINA LAM SIU" },
    { value: "JOHN KOTRAN", label: "JOHN KOTRAN" },
    { value: "KETTY TOMB", label: "KETTY TOMB" },
    { value: "MARCO WILLIAM SILVA", label: "MARCO WILLIAM SILVA" },
    { value: "MARIA ALEJANDRA BARAJAS", label: "MARIA ALEJANDRA BARAJAS" },
    { value: "MARIA TSAREVA", label: "MARIA TSAREVA" },
    { value: "MARIO CARRILLO", label: "MARIO CARRILLO" },
    { value: "NIVINE MOUSSA", label: "NIVINE MOUSSA" },
    { value: "ROBERT BLAIR ALI", label: "ROBERT BLAIR ALI" }
  ]
  